---
title: "Continuação"
author: "Vitória"
date: '2023-03-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
library(umap)
```

## Frequencies
frequencias dos snps por população:

```{r pop_freqs, echo=FALSE, warning=FALSE, message = FALSE}
freqs_cov10 <- fread("/dados/time_clines/data/seqs/align/NE_mincount5_minfreq0.005_cov10.tsv")

ggplot(freqs_cov10) +
  geom_histogram(aes(x= freq)) +
  facet_wrap(~ factor(population,
                      levels = c("ESC97", "CMD97B", "CMA97", "MCT97",
                                 "MFL97", "RVA97", "WVT97", "CMD10",
                                 "HMA09", "JFL10", "MCT09", "SNC10",
                                 "SVT09", "HMA17", "MCT17"))) +
  labs(caption = "min-cov = 10; min-count = 5, min-freq = 0.5%")

freqs_cov15 <- fread("/dados/time_clines/data/seqs/align/NE_mincount10_minfreq0.01_cov15.tsv")

ggplot(freqs_cov15) +
  geom_histogram(aes(x= freq)) +
  facet_wrap(~ factor(population,
                      levels = c("ESC97", "CMD97B", "CMA97", "MCT97",
                                 "MFL97", "RVA97", "WVT97", "CMD10",
                                 "HMA09", "JFL10", "MCT09", "SNC10",
                                 "SVT09", "HMA17", "MCT17"))) +
  labs(caption = "min-cov = 15; min-count = 10, min-freq = 1%")

```

## Inversions

Eu usei o [script](https://github.com/capoony/DrosEU_pipeline) do Martin kapun para calcular as frequências das inverções. Mas fiz só para o segundo call

```{r inv_freq, echo=FALSE, warning=FALSE, message = FALSE}
inv_freq <- fread("/dados/vitoria/invertions_freqs/inversion.freq")

inv_freq <- melt.data.table(inv_freq, measure.vars =  2:15,
                variable.name = "population",
                value.name = "freq")

seq_metadata <- read_tsv("/home/vitoria/clinas/seq_metadata.tsv")
pop_info <- seq_metadata %>%
  select(population, collection_year, latitude)

complete <- inv_freq %>%
  inner_join(pop_info, by = "population") %>%
  mutate(collection_year = case_when( #treats collection_year as character
    collection_year == 1997 ~ "1997", 
    collection_year == 2009 ~ "2009/2010", #and join 2009 and 2010
    collection_year == 2010 ~ "2009/2010",
    collection_year == 2017 ~ "2017"
  ))
  
typeof(complete$collection_year)

complete %>%
  filter(collection_year != "2017") %>%
  ggplot(aes(x = latitude, y = freq)) +
  geom_point(aes(color = collection_year), alpha = 0.5) +
  geom_smooth(aes(color = collection_year), method = 'lm', alpha = 0.2) +
  geom_text(aes(label = population), size = 1.5, nudge_y = 0.07) +
  facet_wrap(~ Inv, nrow = 3) +
  theme_light() +
  labs(title = "Inversions Frequencies")
```

## UMAP

Por sugestão do Murillo, fiz um alguns umaps (Uniform Manifold Approximation and Projection). Mas para falar a verdade eu não entendi muito, nem sei se usei os parâmetros certos:

### 1º Call:

```{r umap2_cov_10, echo=FALSE, warning=FALSE, message = FALSE}
all <- freqs_cov10
all_samples <- all[, .(population, CHROM, POS, freq)]
all_samples[, position2 := paste(CHROM, POS, sep = ":")]
all_samples <- all_samples[, !c("CHROM", "POS")]

pre_pca_table <- dcast.data.table(all_samples, position2 ~ population,
                                  value.var = "freq")

pre_pca_table <- pre_pca_table[,!c("ESC97")]

no_NA_table <- na.omit(pre_pca_table)

pca_table <- no_NA_table %>%
  column_to_rownames(var = "position2")

pca_table <- t(pca_table)

# n_neighbors = 2 ---------------------------------------------------------

SNPs_umap <- umap(pca_table, n_neighbors = 2)

seq_metadata <- read_tsv("/home/vitoria/clinas/seq_metadata.tsv")
pop_info <- seq_metadata %>%
  select(population, collection_year, latitude)


UMAP_tibble <- SNPs_umap$layout %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  rename("population" = "rowname",
         "map1" = "V1",
         "map2" = "V2") %>%
  inner_join(pop_info, by = "population") %>%  #joins tables
  mutate(collection_year = case_when( #treats collection_year as character
    collection_year == 1997 ~ "1997", 
    collection_year == 2009 ~ "2009/2010", #and join 2009 and 2010
    collection_year == 2010 ~ "2009/2010",
    collection_year == 2017 ~ "2017"
  ))


UMAP_tibble %>%
  ggplot(aes(x = map1, y = map2)) +
  geom_point(aes(color = latitude), size = 4, alpha = 0.5) +
  scale_color_viridis_c() +
  geom_text(aes(label = population), size = 1.5, nudge_y = 0.1) +
  labs(caption = "min-cov = 10; min-count = 5, min-freq = 0.5%,
       n_neighbors = 2")



```

```{r umap4_cov_10, echo=FALSE, warning=FALSE, message = FALSE}

SNPs_umap4 <- umap(pca_table, n_neighbors = 4)

UMAP_tibble4 <- SNPs_umap4$layout %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  rename("population" = "rowname",
         "map1" = "V1",
         "map2" = "V2") %>%
  inner_join(pop_info, by = "population") %>%  #joins tables
  mutate(collection_year = case_when( #treats collection_year as character
    collection_year == 1997 ~ "1997", 
    collection_year == 2009 ~ "2009/2010", #and join 2009 and 2010
    collection_year == 2010 ~ "2009/2010",
    collection_year == 2017 ~ "2017"
  ))


UMAP_tibble4 %>%
  ggplot(aes(x = map1, y = map2)) +
  geom_point(aes(color = latitude), size = 4, alpha = 0.5) +
  scale_color_viridis_c() +
  geom_text(aes(label = population), size = 1.5, nudge_y = 0.1) +
  labs(caption = "min-cov = 10; min-count = 5, min-freq = 0.5%,
       n_neighbors = 4")

```

### 2º Call:

```{r umap2_cov_15, echo=FALSE, warning=FALSE, message = FALSE}
all_cov15 <- freqs_cov15
all_samples <- all_cov15[, .(population, CHROM, POS, freq)]
all_samples[, position2 := paste(CHROM, POS, sep = ":")]
all_samples <- all_samples[, !c("CHROM", "POS")]

pre_pca_table <- dcast.data.table(all_samples, position2 ~ population,
                                  value.var = "freq")

pre_pca_table <- pre_pca_table[,!c("ESC97")]

no_NA_table <- na.omit(pre_pca_table)

pca_table <- no_NA_table %>%
  column_to_rownames(var = "position2")

pca_table <- t(pca_table)
# n_neighbors = 2 ---------------------------------------------------------

SNPs_umap <- umap(pca_table, n_neighbors = 2)

seq_metadata <- read_tsv("/home/vitoria/clinas/seq_metadata.tsv")
pop_info <- seq_metadata %>%
  select(population, collection_year, latitude)


UMAP_tibble <- SNPs_umap$layout %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  rename("population" = "rowname",
         "map1" = "V1",
         "map2" = "V2") %>%
  inner_join(pop_info, by = "population") %>%  #joins tables
  mutate(collection_year = case_when( #treats collection_year as character
    collection_year == 1997 ~ "1997", 
    collection_year == 2009 ~ "2009/2010", #and join 2009 and 2010
    collection_year == 2010 ~ "2009/2010",
    collection_year == 2017 ~ "2017"
  ))


UMAP_tibble %>%
  ggplot(aes(x = map1, y = map2)) +
  geom_point(aes(color = latitude), size = 4, alpha = 0.5) +
  scale_color_viridis_c() +
  geom_text(aes(label = population), size = 1.5, nudge_y = 0.1) +
  labs(caption = "min-cov = 15; min-count = 10, min-freq = 1%,
       n_neighbors = 2")


```

```{r umap4_cov_15, echo=FALSE, warning=FALSE, message = FALSE}
# n_neighbors= 4 ----------------------------------------------------------

SNPs_umap4 <- umap(pca_table, n_neighbors = 4)

UMAP_tibble4 <- SNPs_umap4$layout %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  rename("population" = "rowname",
         "map1" = "V1",
         "map2" = "V2") %>%
  inner_join(pop_info, by = "population") %>%  #joins tables
  mutate(collection_year = case_when( #treats collection_year as character
    collection_year == 1997 ~ "1997", 
    collection_year == 2009 ~ "2009/2010", #and join 2009 and 2010
    collection_year == 2010 ~ "2009/2010",
    collection_year == 2017 ~ "2017"
  ))


UMAP_tibble4 %>%
  ggplot(aes(x = map1, y = map2)) +
  geom_point(aes(color = latitude), size = 4, alpha = 0.5) +
  scale_color_viridis_c() +
  geom_text(aes(label = population), size = 1.5, nudge_y = 0.1) +
  labs(caption = "min-cov = 15; min-count = 10, min-freq = 1%,
       n_neighbors = 4")

```


